name: gatus-snitcher
description: "Report success or error to a Gatus external endpoint via its API"
author: "gatus-snitcher maintainers"
branding:
  icon: activity
  color: blue

inputs:
  auth-header:
    description: "HTTP header name used to pass the token (default: Authorization)"
    required: false
    default: Authorization
  auth-scheme:
    description: "Auth scheme prefix before token (e.g., Bearer). Leave empty for raw token."
    required: false
    default: Bearer
  base-url:
    description: "Base URL of your Gatus instance (e.g., https://status.example.com)"
    required: true
  duration:
    description: "Optional duration for the run as a duration string (e.g., 10s, 250ms)."
    required: false
  dry-run:
    description: "If true, don't send the request, just log"
    required: false
    default: "false"
  endpoint-path:
    description: "Base API path for reporting (advanced). Defaults to /api/v1/endpoints per Gatus docs"
    required: false
    default: /api/v1/endpoints
  endpoint-suffix:
    description: "Suffix appended after the key (advanced). Defaults to /external per Gatus docs"
    required: false
    default: /external
  error-message:
    description: "Optional message describing the failure"
    required: false
  extra-headers:
    description: "Additional HTTP headers as JSON or newline-delimited 'Key: Value' entries (e.g., CF-Access-Client-Id, CF-Access-Client-Secret)"
    required: false
  group:
    description: "Gatus group of the external endpoint"
    required: true
  mode:
    description: "Operation mode: start (record timer) or report (send to Gatus). Defaults to report"
    required: false
    default: report
  name:
    description: "Gatus name of the external endpoint"
    required: true
  status:
    description: "Outcome to report: success or error"
    required: false
    default: success
  timeout-ms:
    description: "HTTP request timeout in milliseconds"
    required: false
    default: "15000"
  timer-id:
    description: "Optional timer ID to namespace the start time across steps (defaults to derived endpoint key)"
    required: false
  token:
    description: "API token used to authenticate against Gatus"
    required: true

outputs:
  endpoint:
    description: "Computed endpoint URL used for reporting"
  http-status:
    description: "HTTP status code returned by Gatus"
  status:
    description: "Status reported to Gatus (success or error)"

runs:
  using: node20
  main: dist/index.js
